#!/bin/dash
MYUID=`id -u`
if [ "$MYUID" -ne 0 ]; then
    echo "You are root"
else
    echo "You are the non-root user with uid $MYUID"
fi


## Check for root privileges
#!/bin/bash
#if (($EUID != 0)); then
MYUID=`id -u`
if [ $MYUID -ne 0 ]; then
#  if [[ -t 1 ]]; then
    sudo "$0" "$@"
#  else
#    exec 1>output_file
#    gksu "$0 $@"
#  fi
#  exit
fi

#if [ "$EUID" -ne 0 ]; then
#   echo "This script must be run as root" 1>&2
#   exit 1
#fi

